name: Build & Test

on:
    workflow_dispatch:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install & Build
              run: npm ci
            - name: Build
              run: npm run build
            - name: Linting
              run: npm run lint
            - name: Testing
              run: npm run test
